reviews:
  high_level_summary: false
  estimate_code_review_effort: false
  in_progress_fortune: false
  poem: false
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
