import { animate } from '../../util/animation';
import cycleRestrict from '../../util/cycleRestrict';
import Deferred from '../../util/Deferred';
import generateUniqueId from '../../util/generateUniqueId';
import launchMediaWorkers, { MAX_WORKERS } from '../../util/launchMediaWorkers';
import { IS_ANDROID, IS_IOS, IS_SAFARI } from '../../util/windowEnvironment';
import { requestMeasure, requestMutation } from '../fasterdom/fasterdom';

interface Params {
  size: number;
  shouldStretch?: boolean;
  noLoop?: boolean;
  quality?: number;
  isLowPriority?: boolean;
  coords?: { x: number; y: number };
}

const WAITING = Symbol('WAITING');
type Frame =
  undefined
  | typeof WAITING
  | ImageBitmap;

const HIGH_PRIORITY_QUALITY = (IS_ANDROID || IS_IOS) ? 0.75 : 1;
const LOW_PRIORITY_QUALITY = IS_ANDROID ? 0.5 : 0.75;
const LOW_PRIORITY_QUALITY_SIZE_THRESHOLD = 24;
const HIGH_PRIORITY_CACHE_MODULO = IS_SAFARI ? 2 : 4;
const LOW_PRIORITY_CACHE_MODULO = 0;

const workers = launchMediaWorkers().map(({ connector }) => connector);
const instancesByRenderId = new Map<string, RLottie>();

const PENDING_CANVAS_RESIZES = new WeakMap<HTMLCanvasElement, Promise<void>>();

let lastWorkerIndex = -1;

class RLottie {
  // Config

  private views = new Map<string, {
    canvas: HTMLCanvasElement;
    ctx: CanvasRenderingContext2D;
    isLoaded?: boolean;
    isPaused?: boolean;
    isSharedCanvas?: boolean;
    coords?: Params['coords'];
    onLoad?: NoneToVoidFunction;
  }>();

  private imgSize!: number;

  private imageData!: ImageData;

  private msPerFrame = 1000 / 60;

  private reduceFactor = 1;

  private cacheModulo!: number;

  private workerIndex!: number;

  private frames: Frame[] = [];

  private framesCount?: number;

  // State

  private isAnimating = false;

  private isWaiting = true;

  private isEnded = false;

  private isDestroyed = false;

  private isRendererInited = false;

  private isChangingData = false;

  private pendingGoToFirstFrame = false;

  private approxFrameIndex = 0;

  private prevFrameIndex = -1;

  private stopFrameIndex? = 0;

  private speed = 1;

  private direction: 1 | -1 = 1;

  private lastRenderAt?: number;

  private colorGeneration = 0;

  static init(...args: ConstructorParameters<typeof RLottie>) {
    const [
      , canvas,
      renderId,
      params,
      viewId = generateUniqueId(), ,
      onLoad,
    ] = args;
    let instance = instancesByRenderId.get(renderId);

    if (!instance) {
      instance = new RLottie(...args);
      instancesByRenderId.set(renderId, instance);
    } else {
      instance.addView(viewId, canvas, onLoad, params?.coords);
    }

    return instance;
  }

  constructor(
    private tgsUrl: string,
    private container: HTMLDivElement | HTMLCanvasElement,
    private renderId: string,
    private params: Params,
    viewId: string = generateUniqueId(),
    private customColor?: [number, number, number],
    private onLoad?: NoneToVoidFunction | undefined,
    private onEnded?: (isDestroyed?: boolean) => void,
    private onLoop?: () => void,
  ) {
    this.addView(viewId, container, onLoad, params.coords);
    this.initConfig();
    this.initRenderer();
  }

  public removeView(viewId: string) {
    const {
      canvas, ctx, isSharedCanvas, coords,
    } = this.views.get(viewId)!;

    if (isSharedCanvas) {
      ctx.clearRect(coords!.x, coords!.y, this.imgSize, this.imgSize);
    } else {
      canvas.remove();
    }

    this.views.delete(viewId);

    if (!this.views.size) {
      this.destroy();
    }
  }

  isPlaying() {
    return this.isAnimating || this.isWaiting;
  }

  play(forceRestart = false, viewId?: string) {
    if (viewId) {
      this.views.get(viewId)!.isPaused = false;
    }

    if (this.isEnded && forceRestart) {
      this.approxFrameIndex = Math.floor(0);
    }

    this.stopFrameIndex = undefined;
    this.direction = 1;
    this.doPlay();
  }

  pause(viewId?: string) {
    this.lastRenderAt = undefined;

    if (viewId) {
      this.views.get(viewId)!.isPaused = true;

      const areAllContainersPaused = Array.from(this.views.values()).every(({ isPaused }) => isPaused);
      if (!areAllContainersPaused) {
        return;
      }
    }

    if (this.isWaiting) {
      this.stopFrameIndex = this.approxFrameIndex;
    } else {
      this.isAnimating = false;
    }

    if (!this.params.isLowPriority) {
      this.frames = this.frames.map((frame, i) => {
        // `WAITING` means the frame is already being generated by the worker, so dropping it loses the data
        if (i === this.prevFrameIndex || frame === WAITING) {
          return frame;
        }

        frame?.close();

        return undefined;
      });
    }
  }

  goToFirstFrame(viewId?: string) {
    if (viewId) {
      const view = this.views.get(viewId);
      if (view) view.isPaused = false;
    }

    if (this.framesCount === undefined) {
      this.pendingGoToFirstFrame = true;
      return;
    }

    this.approxFrameIndex = 0;
    this.stopFrameIndex = 0;
    this.direction = 1;
    this.doPlay();
  }

  playSegment([startFrameIndex, stopFrameIndex]: [number, number], forceRestart = false, viewId?: string) {
    if (viewId) {
      this.views.get(viewId)!.isPaused = false;
    }

    const frameIndex = Math.round(this.approxFrameIndex);
    this.stopFrameIndex = Math.floor(stopFrameIndex / this.reduceFactor);
    if (frameIndex !== stopFrameIndex || forceRestart) {
      this.approxFrameIndex = Math.floor(startFrameIndex / this.reduceFactor);
    }
    this.direction = startFrameIndex < stopFrameIndex ? 1 : -1;

    this.doPlay();
  }

  setSpeed(speed: number) {
    this.speed = speed;
  }

  setNoLoop(noLoop?: boolean) {
    this.params.noLoop = noLoop;
  }

  async setSharedCanvasCoords(viewId: string, newCoords: Params['coords']) {
    const containerInfo = this.views.get(viewId)!;
    const {
      canvas, ctx,
    } = containerInfo;

    const isCanvasDirty = !canvas.dataset.isJustCleaned || canvas.dataset.isJustCleaned === 'false';

    if (!isCanvasDirty) {
      await PENDING_CANVAS_RESIZES.get(canvas);
    }

    let [canvasWidth, canvasHeight] = [canvas.width, canvas.height];

    if (isCanvasDirty) {
      const sizeFactor = this.calcSizeFactor();
      ([canvasWidth, canvasHeight] = ensureCanvasSize(canvas, sizeFactor));
      ctx.clearRect(0, 0, canvasWidth, canvasHeight);
      canvas.dataset.isJustCleaned = 'true';
      requestMeasure(() => {
        canvas.dataset.isJustCleaned = 'false';
      });
    }

    containerInfo.coords = {
      x: Math.round((newCoords?.x || 0) * canvasWidth),
      y: Math.round((newCoords?.y || 0) * canvasHeight),
    };

    const frame = this.getFrame(this.prevFrameIndex) || this.getFrame(Math.round(this.approxFrameIndex));

    if (frame && frame !== WAITING) {
      ctx.drawImage(frame, containerInfo.coords.x, containerInfo.coords.y);
    }
  }

  private addView(
    viewId: string,
    container: HTMLDivElement | HTMLCanvasElement,
    onLoad?: NoneToVoidFunction,
    coords?: Params['coords'],
  ) {
    const sizeFactor = this.calcSizeFactor();

    let imgSize: number;

    if (container instanceof HTMLDivElement) {
      if (!(container.parentNode instanceof HTMLElement)) {
        throw new Error('[RLottie] Container is not mounted');
      }

      const { size, shouldStretch } = this.params;

      imgSize = Math.round(size * sizeFactor);

      if (!this.imgSize) {
        this.imgSize = imgSize;
        this.imageData = new ImageData(imgSize, imgSize);
      }

      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d')!;

      if (shouldStretch) {
        canvas.style.width = '100%';
      } else {
        canvas.style.width = `${size}px`;
        canvas.style.height = `${size}px`;
      }

      canvas.style.display = 'block';

      canvas.width = imgSize;
      canvas.height = imgSize;

      // `play`, `pause` and `removeView` can arrive before the mutation below, so the view is
      // registered right away. The canvas is already sized - it can be drawn into before it is
      // in the DOM.
      this.views.set(viewId, {
        canvas, ctx, onLoad,
      });

      requestMutation(() => {
        if (this.views.get(viewId)?.canvas === canvas) {
          container.appendChild(canvas);
        }
      });
    } else {
      if (!container.isConnected) {
        throw new Error('[RLottie] Shared canvas is not mounted');
      }

      const canvas = container;
      const ctx = canvas.getContext('2d')!;

      imgSize = Math.round(this.params.size * sizeFactor);

      if (!this.imgSize) {
        this.imgSize = imgSize;
        this.imageData = new ImageData(imgSize, imgSize);
      }

      const [canvasWidth, canvasHeight] = ensureCanvasSize(canvas, sizeFactor);

      this.views.set(viewId, {
        canvas,
        ctx,
        isSharedCanvas: true,
        coords: {
          x: Math.round(coords!.x * canvasWidth),
          y: Math.round(coords!.y * canvasHeight),
        },
        onLoad,
      });
    }

    if (this.isRendererInited) {
      this.doPlay();
    }
  }

  private calcSizeFactor() {
    const {
      size,
      isLowPriority,
      // Reduced quality only looks acceptable on big enough images
      quality = isLowPriority && (!size || size > LOW_PRIORITY_QUALITY_SIZE_THRESHOLD)
        ? LOW_PRIORITY_QUALITY : HIGH_PRIORITY_QUALITY,
    } = this.params;

    // Reduced quality only looks acceptable on high DPR screens
    return Math.max(window.devicePixelRatio * quality, 1);
  }

  private destroy() {
    this.isDestroyed = true;
    this.pause();
    this.clearCache();
    this.destroyRenderer();

    instancesByRenderId.delete(this.renderId);
  }

  private clearCache() {
    this.frames.forEach((frame) => {
      if (frame && frame !== WAITING) {
        frame.close();
      }
    });

    // Help GC
    this.imageData = undefined as any;
    this.frames = [];
  }

  private initConfig() {
    const { isLowPriority } = this.params;

    this.cacheModulo = isLowPriority ? LOW_PRIORITY_CACHE_MODULO : HIGH_PRIORITY_CACHE_MODULO;
  }

  setColor(newColor: [number, number, number] | undefined) {
    if (areRgbEqual(this.customColor, newColor)) {
      return;
    }
    this.customColor = newColor;

    // Push the new color to the worker eagerly so future `renderFrames` use it. Skipped before
    // init because the worker has no renderer entry yet — `onRendererInit` will resync.
    if (this.isRendererInited) {
      void workers[this.workerIndex].request({
        name: 'rlottie:setColor',
        args: [this.renderId, newColor],
      });
    }

    const wasActive = this.isAnimating || this.isWaiting;

    // Stop the animate loop and drop cached bitmaps; in-flight `renderFrames` callbacks are
    // dropped safely via the WAITING-marker check in `onFrameLoad` / `onColorRefreshFrame`.
    this.isAnimating = false;
    this.lastRenderAt = undefined;
    this.frames.forEach((frame) => {
      if (frame && frame !== WAITING) {
        frame.close();
      }
    });
    this.frames = [];
    this.prevFrameIndex = -1;

    // Defer the manual repaint while init or `changeData` is in flight: their completion
    // handlers will resync color (init) and run `doPlay` which fetches fresh frames.
    // `onRendererInit` resumes only through this flag, so an idle sticker needs it set too -
    // otherwise the cache stays empty and no frame is ever requested.
    if (!this.isRendererInited || this.isChangingData) {
      this.isWaiting = true;
      return;
    }

    // Repaint the current frame manually. Going through `doPlay` alone is not enough — its
    // draw branch skips views with `isPaused`, leaving paused stickers (e.g. nav-bar icons)
    // stuck in the old color until the next hover.
    const frameIndex = Math.round(this.approxFrameIndex);
    this.frames[frameIndex] = WAITING;
    this.colorGeneration++;
    const generation = this.colorGeneration;
    const hasActiveView = Array.from(this.views.values()).some(({ isPaused }) => !isPaused);
    const shouldResume = wasActive && hasActiveView;
    const handleSettled = () => {
      this.dropUndeliveredFrame(generation, frameIndex, shouldResume);
    };

    void workers[this.workerIndex].request({
      name: 'rlottie:renderFrames',
      args: [
        this.renderId,
        frameIndex,
        (loadedIndex: number, imageBitmap: ImageBitmap) => {
          this.onColorRefreshFrame(generation, loadedIndex, imageBitmap, shouldResume);
        },
      ],
    }).then(handleSettled, handleSettled);
  }

  private initRenderer(isRetry = false) {
    this.workerIndex = cycleRestrict(MAX_WORKERS, ++lastWorkerIndex);

    void workers[this.workerIndex].request({
      name: 'rlottie:init',
      args: [
        this.renderId,
        this.tgsUrl,
        this.imgSize,
        this.params.isLowPriority || false,
        this.customColor,
        this.onRendererInit.bind(this),
      ],
    }).catch(() => {
      if (!isRetry && !this.isDestroyed) {
        this.initRenderer(true);
      }
    });
  }

  private destroyRenderer() {
    void workers[this.workerIndex].request({
      name: 'rlottie:destroy',
      args: [this.renderId],
    });
  }

  private onRendererInit(reduceFactor: number, msPerFrame: number, framesCount: number) {
    this.isRendererInited = true;
    this.reduceFactor = reduceFactor;
    this.msPerFrame = msPerFrame;
    this.framesCount = framesCount;

    // Resync color: a `setColor` racing with the async worker init would have no-oped on the
    // worker (renderer entry didn't exist yet). Re-send the current value to guarantee the
    // upcoming `renderFrames` use the right tint.
    void workers[this.workerIndex].request({
      name: 'rlottie:setColor',
      args: [this.renderId, this.customColor],
    });

    if (this.pendingGoToFirstFrame) {
      this.pendingGoToFirstFrame = false;
      this.approxFrameIndex = 0;
      this.stopFrameIndex = 0;
      this.direction = 1;
      this.doPlay();
    } else if (this.isWaiting) {
      this.doPlay();
    }
  }

  changeData(tgsUrl: string) {
    this.isChangingData = true;
    this.isAnimating = false;
    this.isWaiting = false;
    this.lastRenderAt = undefined;
    this.stopFrameIndex = undefined;
    this.prevFrameIndex = -1;

    this.frames.forEach((frame) => {
      if (frame && frame !== WAITING) {
        frame.close();
      }
    });
    this.frames = [];
    // Invalidate in-flight `renderFrames` requests issued against the previous lottie data —
    // their callbacks would otherwise satisfy a fresh WAITING marker at the same frame index.
    this.colorGeneration++;

    this.tgsUrl = tgsUrl;
    this.initConfig();

    // If the request fails, `onChangeData` never runs, and no new frames are requested
    // while `isChangingData` is set.
    void workers[this.workerIndex].request({
      name: 'rlottie:changeData',
      args: [
        this.renderId,
        this.tgsUrl,
        this.params.isLowPriority || false,
        this.onChangeData.bind(this),
      ],
    }).catch(() => {
      this.isChangingData = false;
      // The worker still has the old animation, so it can be played. Its frames were dropped,
      // so ask for them again - without this the canvas stops on the last drawn frame.
      this.doPlay();
    });
  }

  private onChangeData(reduceFactor: number, msPerFrame: number, framesCount: number) {
    this.reduceFactor = reduceFactor;
    this.msPerFrame = msPerFrame;
    this.framesCount = framesCount;
    this.isWaiting = false;
    this.isAnimating = false;
    this.isChangingData = false;

    if (this.pendingGoToFirstFrame) {
      this.pendingGoToFirstFrame = false;
      this.approxFrameIndex = 0;
      this.stopFrameIndex = 0;
      this.direction = 1;
    }

    this.doPlay();
  }

  private doPlay() {
    if (!this.framesCount) {
      return;
    }

    if (this.isDestroyed) {
      return;
    }

    if (this.isAnimating) {
      return;
    }

    if (!this.isWaiting) {
      this.lastRenderAt = undefined;
    }

    this.isEnded = false;
    this.isAnimating = true;
    this.isWaiting = false;

    animate(() => {
      if (this.isDestroyed) {
        return false;
      }

      // Paused from outside
      if (!this.isAnimating) {
        const areAllLoaded = Array.from(this.views.values()).every(({ isLoaded }) => isLoaded);
        if (areAllLoaded) {
          return false;
        }
      }

      const frameIndex = Math.round(this.approxFrameIndex);
      const frame = this.getFrame(frameIndex);
      if (!frame || frame === WAITING) {
        if (!frame) {
          this.requestFrame(frameIndex);
        }

        this.isAnimating = false;
        this.isWaiting = true;
        return false;
      }

      if (this.cacheModulo && frameIndex % this.cacheModulo === 0) {
        this.cleanupPrevFrame(frameIndex);
      }

      if (frameIndex !== this.prevFrameIndex) {
        this.views.forEach((containerData) => {
          const {
            ctx, isLoaded, isPaused, coords: { x, y } = {}, onLoad,
          } = containerData;

          if (!isLoaded || !isPaused) {
            ctx.clearRect(x || 0, y || 0, this.imgSize, this.imgSize);
            ctx.drawImage(frame, x || 0, y || 0);
          }

          if (!isLoaded) {
            containerData.isLoaded = true;
            onLoad?.();
          }
        });

        this.prevFrameIndex = frameIndex;
      }

      const now = Date.now();
      const currentSpeed = this.lastRenderAt ? this.msPerFrame / (now - this.lastRenderAt) : 1;
      const delta = (this.direction * this.speed) / currentSpeed;
      const expectedNextFrameIndex = Math.round(this.approxFrameIndex + delta);

      this.lastRenderAt = now;

      // Forward animation finished
      if (delta > 0 && (frameIndex === this.framesCount! - 1 || expectedNextFrameIndex > this.framesCount! - 1)) {
        if (this.params.noLoop) {
          this.isAnimating = false;
          this.isEnded = true;
          this.onEnded?.();
          return false;
        }
        this.onLoop?.();

        this.approxFrameIndex = 0;

        // Backward animation finished
      } else if (delta < 0 && (frameIndex === 0 || expectedNextFrameIndex < 0)) {
        if (this.params.noLoop) {
          this.isAnimating = false;
          this.isEnded = true;
          this.onEnded?.();
          return false;
        }
        this.onLoop?.();

        this.approxFrameIndex = this.framesCount! - 1;

        // Stop frame reached
      } else if (
        this.stopFrameIndex !== undefined
        && (frameIndex === this.stopFrameIndex
          || (
            (delta > 0 && expectedNextFrameIndex > this.stopFrameIndex)
            || (delta < 0 && expectedNextFrameIndex < this.stopFrameIndex)
          ))
      ) {
        this.stopFrameIndex = undefined;
        this.isAnimating = false;
        return false;

        // Preparing next frame
      } else {
        this.approxFrameIndex += delta;
      }

      const nextFrameIndex = Math.round(this.approxFrameIndex);

      if (!this.getFrame(nextFrameIndex)) {
        this.requestFrame(nextFrameIndex);
        this.isWaiting = true;
        this.isAnimating = false;
        return false;
      }

      return true;
    }, requestMutation);
  }

  private getFrame(frameIndex: number) {
    return this.frames[frameIndex];
  }

  private requestFrame(frameIndex: number) {
    if (this.isChangingData) {
      return;
    }
    this.frames[frameIndex] = WAITING;
    // Capture generation at send time. `setColor` / `changeData` bump it; the WAITING marker
    // alone can't tell apart "waiting for the request I just sent" from "waiting for a request
    // sent before the cache reset", so a stale bitmap could otherwise be accepted at the same
    // frame index.
    const generation = this.colorGeneration;
    const handleSettled = () => {
      this.dropUndeliveredFrame(generation, frameIndex, this.isWaiting);
    };

    void workers[this.workerIndex].request({
      name: 'rlottie:renderFrames',
      args: [
        this.renderId,
        frameIndex,
        (loadedIndex: number, imageBitmap: ImageBitmap) => {
          this.onFrameLoad(generation, loadedIndex, imageBitmap);
        },
      ],
    }).then(handleSettled, handleSettled);
  }

  // A request can end without a bitmap: it fails, or the worker resolves it doing nothing
  // because its renderer is already gone. The `WAITING` marker would then occupy the slot
  // forever - `doPlay` treats it as a frame that is about to arrive and stops the loop, and
  // `pause` keeps such markers. The callback message always precedes the response, so a
  // delivered frame is already in the slot by now and the check below leaves it alone.
  private dropUndeliveredFrame(generation: number, frameIndex: number, shouldResume: boolean) {
    if (
      this.isDestroyed
      || generation !== this.colorGeneration
      || this.frames[frameIndex] !== WAITING
    ) {
      return;
    }

    this.frames[frameIndex] = undefined;

    if (shouldResume) {
      this.doPlay();
    }
  }

  private cleanupPrevFrame(frameIndex: number) {
    if (this.framesCount! < 3) {
      return;
    }

    const prevFrameIndex = cycleRestrict(this.framesCount!, frameIndex - 1);
    this.frames[prevFrameIndex] = undefined;
  }

  private onFrameLoad(generation: number, frameIndex: number, imageBitmap: ImageBitmap) {
    // Drop stale arrivals: cache reset (`setColor`/`changeData`) bumped the generation, or the
    // slot has been freed/replaced. Close to release the GPU-backed bitmap; otherwise it leaks
    // until the next GC.
    if (
      this.isDestroyed
      || generation !== this.colorGeneration
      || this.frames[frameIndex] !== WAITING
    ) {
      imageBitmap.close();
      return;
    }

    this.frames[frameIndex] = imageBitmap;

    if (this.isWaiting) {
      this.doPlay();
    }
  }

  private onColorRefreshFrame(
    generation: number,
    frameIndex: number,
    imageBitmap: ImageBitmap,
    shouldResume: boolean,
  ) {
    if (
      this.isDestroyed
      || generation !== this.colorGeneration
      || this.frames[frameIndex] !== WAITING
    ) {
      imageBitmap.close();
      return;
    }

    this.frames[frameIndex] = imageBitmap;

    requestMutation(() => {
      if (this.isDestroyed) return;
      this.views.forEach((view) => {
        const { ctx, coords: { x, y } = {}, onLoad } = view;
        ctx.clearRect(x || 0, y || 0, this.imgSize, this.imgSize);
        ctx.drawImage(imageBitmap, x || 0, y || 0);

        // This is the first drawn frame for the view, and until that is reported the preview
        // stays on top of the canvas, hiding the recolored icon
        if (!view.isLoaded) {
          view.isLoaded = true;
          onLoad?.();
        }
      });
      this.prevFrameIndex = frameIndex;

      if (shouldResume && !this.isDestroyed) {
        this.doPlay();
      }
    });
  }
}

function areRgbEqual(
  a: [number, number, number] | undefined,
  b: [number, number, number] | undefined,
) {
  if (a === b) return true;
  if (!a || !b) return false;
  return a[0] === b[0] && a[1] === b[1] && a[2] === b[2];
}

function ensureCanvasSize(canvas: HTMLCanvasElement, sizeFactor: number) {
  const expectedWidth = Math.round(canvas.offsetWidth * sizeFactor);
  const expectedHeight = Math.round(canvas.offsetHeight * sizeFactor);

  if (canvas.width !== expectedWidth || canvas.height !== expectedHeight) {
    const deferred = new Deferred<void>();
    PENDING_CANVAS_RESIZES.set(canvas, deferred.promise);
    requestMutation(() => {
      canvas.width = expectedWidth;
      canvas.height = expectedHeight;
      deferred.resolve();
    });
  }

  return [expectedWidth, expectedHeight];
}

export default RLottie;
